-- Doctor self-registration table (created/updated by JPA ddl-auto=update as well)
CREATE SCHEMA IF NOT EXISTS svc;

CREATE TABLE IF NOT EXISTS svc.doctor_details (
  id                              VARCHAR(36) PRIMARY KEY,
  doctor_id                       VARCHAR(40) NOT NULL UNIQUE,
  first_name                      VARCHAR(255) NOT NULL,
  middle_name                     VARCHAR(255),
  last_name                       VARCHAR(255) NOT NULL,
  gender                          VARCHAR(50) NOT NULL,
  date_of_birth                   DATE NOT NULL,
  profile_photo                   TEXT,
  blood_group                     VARCHAR(20),
  marital_status                  VARCHAR(50),
  mobile_number                   VARCHAR(40) NOT NULL,
  alternate_mobile_number         VARCHAR(40),
  email                           VARCHAR(255) NOT NULL UNIQUE,
  emergency_contact_number        VARCHAR(40),
  residential_address             TEXT NOT NULL,
  city                            VARCHAR(120) NOT NULL,
  state                           VARCHAR(120) NOT NULL,
  country                         VARCHAR(120) NOT NULL,
  postal_code                     VARCHAR(40) NOT NULL,
  medical_registration_number     VARCHAR(120) NOT NULL UNIQUE,
  medical_council_name            VARCHAR(255) NOT NULL,
  registration_date               DATE NOT NULL,
  registration_valid_until        DATE,
  years_of_experience             INTEGER,
  current_designation             VARCHAR(255),
  department                      VARCHAR(255),
  specialization                  VARCHAR(255) NOT NULL,
  sub_specialization              VARCHAR(255),
  qualification                   VARCHAR(255),
  medical_college                 VARCHAR(255),
  graduation_year                 INTEGER,
  hospital_name                   VARCHAR(255),
  clinic_name                     VARCHAR(255),
  hospital_id                     BIGINT,
  branch                          VARCHAR(255),
  consultation_type               VARCHAR(40),
  consultation_fee                DOUBLE PRECISION,
  follow_up_fee                   DOUBLE PRECISION,
  available_days                  VARCHAR(120),
  available_time_slots            VARCHAR(255),
  aadhaar_number                  VARCHAR(40),
  pan_number                      VARCHAR(40),
  passport_number                 VARCHAR(40),
  government_id_upload            TEXT,
  account_holder_name             VARCHAR(255),
  bank_name                       VARCHAR(255),
  account_number                  VARCHAR(80),
  ifsc_code                       VARCHAR(40),
  upi_id                          VARCHAR(120),
  medical_registration_certificate TEXT,
  degree_certificate              TEXT,
  experience_certificate          TEXT,
  identity_proof                  TEXT,
  address_proof                   TEXT,
  passport_size_photograph        TEXT,
  digital_signature               TEXT,
  emergency_contact_name          VARCHAR(255),
  emergency_relationship          VARCHAR(120),
  emergency_contact_phone         VARCHAR(40),
  languages_known                 TEXT,
  biography                       TEXT,
  awards_achievements             TEXT,
  publications                    TEXT,
  research_experience             TEXT,
  memberships                     TEXT,
  status                          VARCHAR(40) NOT NULL DEFAULT 'ACTIVE',
  created_by                      VARCHAR(120),
  created_date                    TIMESTAMPTZ NOT NULL,
  updated_date                    TIMESTAMPTZ,
  last_login                      TIMESTAMPTZ,
  remarks                         TEXT,
  info_correct_confirmed          BOOLEAN NOT NULL DEFAULT FALSE,
  terms_accepted                  BOOLEAN NOT NULL DEFAULT FALSE,
  privacy_policy_accepted         BOOLEAN NOT NULL DEFAULT FALSE
);
